### ISSUE TITLE
Error running crd-request-generator due to SSL error?

### ISSUE THREAD

**Issue by samstearns** [HL7-DaVinci/CRD#288]
Hello,
I was able to install crd-request-generator, but it crashes when I run it.  See below

npm start

> request-generator@0.1.0 start
> concurrently --kill-others "json-server --watch src/db.json -p 3001 --host 0.0.0.0" "react-scripts start"

[0] 
[0]   \{^_^}/ hi!
[0] 
[0]   Loading src/db.json
[0]   Done
[0] 
[0]   Resources
[0]   http://0.0.0.0:3001/public_keys
[0] 
[0]   Home
[0]   http://0.0.0.0:3001
[0] 
[0]   Type s + enter at any time to create a snapshot of the database
[0]   Watching...
[0] 
[1] ℹ ｢wds｣: Project is running at http://192.168.1.89/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/sjs/dev/drlsroot/crd-request-generator/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1] 
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:71:19)
[1]     at Object.createHash (node:crypto:133:10)
[1]     at module.exports (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/util/createHash.js:135:53)
[1]     at NormalModule._initBuildHash (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:417:16)
[1]     at handleParseError (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:471:10)
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:503:5
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:358:12
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[1]     at iterateNormalLoaders (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[1]     at iterateNormalLoaders (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[1] /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/react-scripts/scripts/start.js:19
[1]   throw err;
[1]   ^
[1] 
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:71:19)
[1]     at Object.createHash (node:crypto:133:10)
[1]     at module.exports (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/util/createHash.js:135:53)
[1]     at NormalModule._initBuildHash (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:417:16)
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:452:10
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/webpack/lib/NormalModule.js:323:13
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[1]     at context.callback (/Users/sjs/dev/drlsroot/crd-request-generator/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[1]     at /Users/sjs/dev/drlsroot/crd-request-generator/node_modules/babel-loader/lib/index.js:59:103 {
[1]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[1]   library: 'digital envelope routines',
[1]   reason: 'unsupported',
[1]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[1] }
[1] 
[1] Node.js v18.12.1
[1] react-scripts start exited with code 1
--> Sending SIGTERM to other processes..
[0] json-server --watch src/db.json -p 3001 --host 0.0.0.0 exited with code SIGTERM

**Comment by samstearns** [comment]
Update: I encountered a similar issue when running dtr.

I was able to get both to run by using the command export NODE_OPTIONS=--openssl-legacy-provider from this webpage

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

It sounds like the issue is due to a breaking change in node. I am running node v18

**Comment by bstewartlg** [comment]
The CRD Request Generator and DTR apps are unfortunately currently pegged to Node 16.  The README for each has been updated to specify this.
